const data = {
  products: [
    {
      name: "포르쉐 911",
      slug: "포르쉐 911",
      category: "Shirts",
      image: "/images/p1.jpeg", // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "포르쉐 911",
    },
    {
      name: "포르쉐 박스터",
      slug: "포르쉐 박스터",
      category: "Shirts",
      image: "/images/p2.jpeg",
      price: 250,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "포르쉐 카이렌",
      slug: "포르쉐 카이렌",
      category: "Pants",
      image: "/images/p3.jpeg",
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "포르쉐 911",
      slug: "포르쉐 911",
      category: "Pants",
      image: "/images/p4.jpeg",
      price: 1000,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
module.exports = data;
