const colors = [
  {
    name: "Red",
    value: "#FF0000",
    count: null,
    check: false,
  },
  {
    name: "Orange",
    value: "#FFA500",
    count: null,
    check: false,
  },
  {
    name: "Yellow",
    value: "#FFFF00",
    count: null,
    check: false,
  },
  {
    name: "Olive",
    value: "#808000",
    count: null,
    check: false,
  },
  {
    name: "DarkOlive",
    value: "#6B8E23",
    count: null,
    check: false,
  },
  {
    name: "Green",
    value: "#008000",
    count: null,
    check: false,
  },
  {
    name: "Sky",
    value: "#87CEEB",
    count: null,
    check: false,
  },
  {
    name: "Blue",
    value: "#0000FF",
    count: null,
    check: false,
  },
  {
    name: "LightPurpl",
    value: "#BA55D3",
    count: null,
    check: false,
  },
  {
    name: "MiddlePurp",
    value: "#BA55D3",
    count: null,
    check: false,
  },
  {
    name: "DarkPurpur",
    value: "#9400D3",
    count: null,
    check: false,
  },
  {
    name: "Pink",
    value: "#FF1493",
    count: null,
    check: false,
  },
  {
    name: "LightPink",
    value: "#FFC0CB",
    count: null,
    check: false,
  },
  {
    name: "Bage",
    value: "#F5F5DC",
    count: null,
    check: false,
  },
  {
    name: "LightBage",
    value: "#FAF0E6",
    count: null,
    check: false,
  },
  {
    name: "Lemon",
    value: "#FFFACD",
    count: null,
    check: false,
  },
  {
    name: "Brown",
    value: "#A0522D",
    count: null,
    check: false,
  },
  {
    name: "LightGray",
    value: "#778899",
    count: null,
    check: false,
  },
  {
    name: "Labander",
    value: "#E6E6FA",
    count: null,
    check: false,
  },
  {
    name: "Silver",
    value: "#C0C0C0",
    count: null,
    check: false,
  },
  {
    name: "White",
    value: "#FFFFFF",
    count: null,
    check: false,
  },
  {
    name: "Black",
    value: "#000000",
    count: null,
    check: false,
  },
];
module.exports = { colors };
